/**
 * 詞庫（pg-worddawn）
 *
 * ANSWERS ─ 可能成為答案的五字母英文詞。全部常見、可猜，
 *           其中混入夜市／水果／小吃等台味主題詞（MANGO、GUAVA、BETEL、
 *           LOTUS、PEARL、STALL、NIGHT、SNACK、RAMEN、SUSHI…）。
 * EXTRA_GUESSES ─ 不會當答案、但允許玩家猜的常見五字母詞。
 * ALLOWED ─ ANSWERS ∪ EXTRA_GUESSES；不在此表的輸入一律拒絕。
 */

/** @type {readonly string[]} */
export const ANSWERS = Object.freeze([
  "ABOUT", "ALERT", "ANGEL", "APPLE", "BEACH", "BEGIN", "BERRY", "BETEL",
  "BLAZE", "BLOOM", "BOARD", "BRAVE", "BREAD", "BRICK", "BRUSH", "CABLE",
  "CANDY", "CHAIR", "CHARM", "CHIME", "CLIMB", "CLOCK", "CLOUD", "COAST",
  "CRANE", "CROWD", "CURRY", "DAIRY", "DANCE", "DELTA", "DREAM", "DRIFT",
  "EAGLE", "EARTH", "FEAST", "FIELD", "FLAME", "FLOAT", "FRESH", "FRUIT",
  "GHOST", "GLASS", "GLIDE", "GRACE", "GRAIN", "GRAPE", "GREEN", "GUAVA",
  "HEART", "HONEY", "HOUSE", "ISLET", "JELLY", "JUICE", "KNIFE", "LATCH",
  "LEMON", "LIGHT", "LOTUS", "LUCKY", "MANGO", "MAPLE", "MARCH", "MELON",
  "MERIT", "MONEY", "MOUNT", "MUSIC", "NIGHT", "NOBLE", "NOISE", "NORTH",
  "OCEAN", "ONION", "ORBIT", "PAINT", "PEACH", "PEARL", "PIANO", "PLANT",
  "PLATE", "POINT", "PORCH", "PRIDE", "QUEEN", "QUIET", "RADIO", "RAMEN",
  "RIVER", "ROAST", "ROUND", "SALTY", "SCENT", "SHELL", "SHINE", "SHORE",
  "SMILE", "SMOKE", "SNACK", "SOLAR", "SPARK", "SPICE", "STALL", "STEAM",
  "STONE", "STORM", "SUGAR", "SUSHI", "SWEET", "TABLE", "TEMPO", "THINK",
  "TIGER", "TOAST", "TOWER", "TRAIL", "TRAIN", "TREND", "TRUST", "VALUE",
  "VAPOR", "VIVID", "WATER", "WHALE", "WHEAT", "WHITE", "WINDY", "WORLD",
  "YOUTH", "ZEBRA",
]);

/**
 * 允許猜、但不會被抽為答案的詞（讓開局試探詞更自由）。
 * @type {readonly string[]}
 */
export const EXTRA_GUESSES = Object.freeze([
  "ABIDE", "ABOVE", "ACORN", "ACTOR", "ACUTE", "ADAPT", "ADMIT", "ADOPT",
  "ADORE", "AGENT", "AGILE", "AGREE", "AHEAD", "AISLE", "ALARM", "ALBUM",
  "ALIEN", "ALIGN", "ALIKE", "ALIVE", "ALLEY", "ALLOW", "ALLOY", "ALONE",
  "ALONG", "ALOUD", "ALPHA", "ALTAR", "ALTER", "AMBER", "AMEND", "AMPLE",
  "AMUSE", "ANGER", "ANGLE", "ANGRY", "ANKLE", "ANNOY", "APART", "APRON",
  "ARENA", "ARGUE", "ARISE", "ARMOR", "AROMA", "AROSE", "ARRAY", "ARROW",
  "ASIDE", "ASSET", "ATLAS", "ATTIC", "AUDIO", "AUDIT", "AVOID", "AWAIT",
  "AWAKE", "AWARD", "AWARE", "AWFUL", "BACON", "BADGE", "BADLY", "BAGEL",
  "BAKER", "BANJO", "BARON", "BASIC", "BASIL", "BASIN", "BATCH", "BEARD",
  "BEAST", "BEGAN", "BEGUN", "BEING", "BELLY", "BELOW", "BENCH", "BIRCH",
  "BIRTH", "BISON", "BLACK", "BLADE", "BLAME", "BLAND", "BLANK", "BLAST",
  "BLEAK", "BLEED", "BLEND", "BLESS", "BLIND", "BLINK", "BLISS", "BLOCK",
  "BLOND", "BLOOD", "BLOWN", "BLUFF", "BLUNT", "BLUSH", "BOAST", "BONUS",
  "BOOST", "BOOTH", "BOUND", "BOXER", "BRAID", "BRAIN", "BRAKE", "BRAND",
  "BRASS", "BREAK", "BREED", "BRIBE", "BRIDE", "BRIEF", "BRING", "BRINK",
  "BRISK", "BROAD", "BROKE", "BROOK", "BROOM", "BROTH", "BROWN", "BUDDY",
  "BUGGY", "BUILD", "BUILT", "BULKY", "BUNCH", "BURNT", "BURST", "BUYER",
  "CABIN", "CAMEL", "CANAL", "CANOE", "CARGO", "CAROL", "CARRY", "CARVE",
  "CATCH", "CAUSE", "CEASE", "CEDAR", "CELLO", "CHAIN", "CHALK", "CHANT",
  "CHAOS", "CHART", "CHASE", "CHEAP", "CHEAT", "CHECK", "CHEEK", "CHEER",
  "CHESS", "CHEST", "CHIEF", "CHILD", "CHILI", "CHILL", "CHIRP", "CHOIR",
  "CHOKE", "CHORD", "CHORE", "CHOSE", "CHUNK", "CIDER", "CIGAR", "CIVIL",
  "CLAIM", "CLAMP", "CLASH", "CLASS", "CLEAN", "CLEAR", "CLERK", "CLICK",
  "CLIFF", "CLING", "CLOAK", "CLONE", "CLOSE", "CLOTH", "CLOVE", "CLOWN",
  "COACH", "COBRA", "COCOA", "COLOR", "COMET", "COMIC", "CORAL", "COUCH",
  "COUGH", "COULD", "COUNT", "COURT", "COVER", "CRACK", "CRAFT", "CRAMP",
  "CRASH", "CRATE", "CRAVE", "CRAWL", "CRAZY", "CREAM", "CREEK", "CREEP",
  "CREST", "CRIED", "CRIME", "CRISP", "CROSS", "CROWN", "CRUDE", "CRUEL",
  "CRUMB", "CRUSH", "CRUST", "CURVE", "CYCLE", "DAILY", "DAISY", "DEALT",
  "DEATH", "DEBIT", "DEBUT", "DECAY", "DELAY", "DEMON", "DENIM", "DENSE",
  "DEPOT", "DEPTH", "DEVIL", "DIARY", "DIGIT", "DINER", "DIRTY", "DITCH",
  "DIVER", "DIZZY", "DODGE", "DOING", "DONOR", "DONUT", "DOUBT", "DOUGH",
  "DOZEN", "DRAFT", "DRAIN", "DRAMA", "DRANK", "DRAWN", "DREAD", "DRESS",
  "DRIED", "DRILL", "DRINK", "DRIVE", "DRONE", "DROVE", "DROWN", "DRUNK",
  "DUSTY", "DWELL", "DYING", "EAGER", "EARLY", "EATEN", "EBONY", "EIGHT",
  "EJECT", "ELBOW", "ELDER", "ELECT", "ELITE", "EMAIL", "EMBER", "EMPTY",
  "ENEMY", "ENJOY", "ENTER", "ENTRY", "EPOCH", "EQUAL", "EQUIP", "ERASE",
  "ERROR", "ERUPT", "ESSAY", "ETHIC", "EVENT", "EVERY", "EXACT", "EXCEL",
  "EXILE", "EXIST", "EXTRA", "FABLE", "FAINT", "FAIRY", "FAITH", "FALSE",
  "FANCY", "FATAL", "FAULT", "FAVOR", "FENCE", "FERRY", "FETCH", "FEVER",
  "FEWER", "FIBER", "FIFTH", "FIFTY", "FIGHT", "FINAL", "FINCH", "FIRST",
  "FLAIR", "FLAKE", "FLANK", "FLARE", "FLASH", "FLASK", "FLEET", "FLESH",
  "FLICK", "FLING", "FLINT", "FLOCK", "FLOOD", "FLOOR", "FLOUR", "FLOWN",
  "FLUID", "FLUSH", "FLUTE", "FOCUS", "FOGGY", "FORCE", "FORGE", "FORTH",
  "FORTY", "FORUM", "FOUND", "FOYER", "FRAME", "FRANK", "FRAUD", "FRIED",
  "FRONT", "FROST", "FROWN", "FUNNY", "GAUGE", "GAVEL", "GIANT", "GIVEN",
  "GLARE", "GLEAM", "GLOBE", "GLOOM", "GLORY", "GLOVE", "GOOSE", "GRAND",
  "GRANT", "GRASP", "GRASS", "GRAVE", "GRAVY", "GREAT", "GREET", "GRIEF",
  "GRILL", "GRIND", "GROAN", "GROOM", "GROSS", "GROUP", "GROVE", "GROWN",
  "GUARD", "GUEST", "GUIDE", "GUILD", "GUILT", "HABIT", "HAPPY", "HARSH",
  "HASTE", "HATCH", "HAVEN", "HAZEL", "HEAVY", "HEDGE", "HELLO", "HENCE",
  "HERON", "HOBBY", "HOIST", "HOLLY", "HORSE", "HOTEL", "HOUND", "HUMAN",
  "HUMID", "HUMOR", "HURRY", "IDEAL", "IMAGE", "IMPLY", "INDEX", "INNER",
  "INPUT", "IRONY", "IVORY", "JEANS", "JOINT", "JOLLY", "JUDGE", "JUMBO",
  "KIOSK", "KNEEL", "KNELT", "KNOCK", "KNOWN", "LABEL", "LABOR", "LARGE",
  "LASER", "LATER", "LAUGH", "LAYER", "LEARN", "LEASE", "LEAST", "LEAVE",
  "LEDGE", "LEGAL", "LEVEL", "LEVER", "LIMIT", "LINEN", "LIVER", "LLAMA",
  "LOCAL", "LODGE", "LOGIC", "LOOSE", "LORRY", "LOWER", "LOYAL", "LUNAR",
  "LUNCH", "LYRIC", "MAGIC", "MAJOR", "MAKER", "MANGA", "MANOR", "MAYBE",
  "MAYOR", "MEDAL", "MEDIA", "MERCY", "MERGE", "MERRY", "METAL", "METER",
  "MIDST", "MIGHT", "MINOR", "MINUS", "MIXER", "MODEL", "MOIST", "MOTOR",
  "MOTTO", "MOUSE", "MOUTH", "MOVIE", "MURAL", "NAVAL", "NERVE", "NEVER",
  "NEWLY", "NICHE", "NINJA", "NOVEL", "NURSE", "NYLON", "OFFER", "OFTEN",
  "OLIVE", "OPERA", "ORDER", "ORGAN", "OTHER", "OTTER", "OUGHT", "OUNCE",
  "OUTER", "OWNER", "OXIDE", "PADDY", "PANEL", "PANIC", "PAPER", "PARTY",
  "PASTA", "PATCH", "PATIO", "PAUSE", "PEDAL", "PENNY", "PERCH", "PERIL",
  "PHASE", "PHONE", "PHOTO", "PIECE", "PILOT", "PINCH", "PITCH", "PIVOT",
  "PIZZA", "PLACE", "PLAID", "PLAIN", "PLANE", "PLAZA", "PLUCK", "PLUMB",
  "POLAR", "POLKA", "POUCH", "POUND", "POWER", "PRESS", "PRICE",
  "PRINT", "PRIOR", "PRIZE", "PROBE", "PRONE", "PROOF", "PROSE", "PROUD",
  "PROVE", "PRUNE", "PULSE", "PUNCH", "PUPIL", "PUREE", "QUACK", "QUAKE",
  "QUART", "QUEST", "QUEUE", "QUICK", "QUILT", "QUIRK", "QUOTA", "QUOTE",
  "RAINY", "RALLY", "RANCH", "RANGE", "RAPID", "RATIO", "RAVEN", "REACH",
  "REACT", "READY", "REALM", "REBEL", "RECAP", "REFER", "REIGN", "RELAX",
  "RELAY", "RELIC", "REMIT", "RENEW", "REPAY", "REPLY", "RESET", "RESIN",
  "RETRY", "REVEL", "RHYME", "RIDGE", "RIGHT", "RIGID", "RINSE", "RISEN",
  "RISKY", "RIVAL", "ROBIN", "ROBOT", "ROCKY", "ROGUE", "ROOMY", "ROOST",
  "ROTOR", "ROUGH", "ROUTE", "ROYAL", "RUGBY", "RULER", "RURAL", "SADLY",
  "SAINT", "SALAD", "SALON", "SANDY", "SAUCE", "SAVOR", "SCALE", "SCARF",
  "SCENE", "SCOLD", "SCOPE", "SCORE", "SCOUT", "SCRAP", "SCREW", "SCRUB",
  "SEIZE", "SENSE", "SERVE", "SETUP", "SEVEN", "SHACK", "SHADE", "SHAFT",
  "SHAKE", "SHALL", "SHAME", "SHAPE", "SHARE", "SHARK", "SHARP", "SHAVE",
  "SHEEP", "SHEER", "SHEET", "SHELF", "SHIFT", "SHIRT", "SHOCK", "SHOOK",
  "SHOOT", "SHORT", "SHOUT", "SHOWN", "SHRUB", "SHRUG", "SIEGE", "SIGHT",
  "SILKY", "SILLY", "SINCE", "SIREN", "SIXTH", "SIXTY", "SKATE", "SKILL",
  "SKIRT", "SKULL", "SLANT", "SLATE", "SLEEK", "SLEEP", "SLEPT", "SLICE",
  "SLIDE", "SLOPE", "SLOTH", "SMALL", "SMART", "SMASH", "SMELL", "SNAIL",
  "SNAKE", "SNEAK", "SNOWY", "SOAPY", "SOBER", "SOLID", "SOLVE", "SONIC",
  "SORRY", "SOUND", "SOUTH", "SPACE", "SPADE", "SPARE", "SPEAK", "SPEND",
  "SPENT", "SPILL", "SPINE", "SPIRE", "SPLIT", "SPOIL", "SPOKE", "SPOON",
  "SPORT", "SPRAY", "SQUAD", "STACK", "STAFF", "STAGE", "STAIN", "STAIR",
  "STAKE", "STAMP", "STAND", "STARE", "START", "STATE", "STEAK", "STEAL",
  "STEEL", "STEEP", "STEER", "STERN", "STICK", "STIFF", "STILL", "STING",
  "STOCK", "STOOD", "STOOL", "STOUT", "STOVE", "STRAP", "STRAW", "STRAY",
  "STRIP", "STUCK", "STUDY", "STUFF", "STUNT", "STYLE", "SUITE", "SUNNY",
  "SUPER", "SURGE", "SWAMP", "SWEAR", "SWEAT", "SWEEP", "SWELL", "SWEPT",
  "SWIFT", "SWING", "SWORD", "SWORE", "SWORN", "SYRUP", "TABOO", "TALON",
  "TANGO", "TAPER", "TARDY", "TASTE", "TASTY", "TAUNT", "TEACH", "TEMPT",
  "TENOR", "TENSE", "TENTH", "TERSE", "THANK", "THEFT", "THEIR", "THEME",
  "THERE", "THESE", "THICK", "THIEF", "THIGH", "THING", "THIRD", "THORN",
  "THOSE", "THREE", "THREW", "THROW", "THUMB", "TIDAL", "TIGHT", "TIMER",
  "TIRED", "TITLE", "TODAY", "TOKEN", "TONIC", "TOOTH", "TOPIC", "TORCH",
  "TOTAL", "TOUCH", "TOUGH", "TOXIC", "TRACE", "TRACK", "TRACT", "TRADE",
  "TRASH", "TREAT", "TRIAL", "TRIBE", "TRICK", "TRIED", "TROOP", "TROUT",
  "TRUCK", "TRULY", "TRUNK", "TRUTH", "TULIP", "TUNIC", "TURBO", "TUTOR",
  "TWEED", "TWICE", "TWIST", "ULTRA", "UNCLE", "UNDER", "UNDUE", "UNFIT",
  "UNION", "UNITE", "UNITY", "UNTIL", "UPPER", "UPSET", "URBAN", "URGED",
  "USAGE", "USHER", "USUAL", "UTTER", "VAGUE", "VALID", "VALVE", "VAULT",
  "VENUE", "VERGE", "VERSE", "VIDEO", "VIGIL", "VILLA", "VINYL", "VIRUS",
  "VISIT", "VISOR", "VISTA", "VITAL", "VOCAL", "VODKA", "VOICE", "VOTER",
  "WAFER", "WAGON", "WAIST", "WAIVE", "WALTZ", "WASTE", "WATCH", "WEARY",
  "WEAVE", "WEDGE", "WEEDY", "WEIGH", "WEIRD", "WHARF", "WHEEL", "WHERE",
  "WHICH", "WHILE", "WHIRL", "WHISK", "WHOLE", "WHOSE", "WIDEN", "WIDER",
  "WIDOW", "WIDTH", "WIELD", "WINCE", "WITCH", "WOMAN", "WOMEN", "WOODY",
  "WOULD", "WOUND", "WOVEN", "WRECK", "WRIST", "WRITE", "WRONG", "WROTE",
  "YACHT", "YEARN", "YEAST", "YIELD", "YOUNG", "ZESTY",
]);

/** 所有可送出的猜測（答案表 ∪ 額外猜測表）。 */
export const ALLOWED = Object.freeze(
  Array.from(new Set([...ANSWERS, ...EXTRA_GUESSES])).sort()
);

const ALLOWED_SET = new Set(ALLOWED);

/**
 * 這個詞是否可以被送出（已正規化為大寫）。
 * @param {string} word
 * @returns {boolean}
 */
export function isAllowedGuess(word) {
  return ALLOWED_SET.has(String(word ?? "").toUpperCase());
}
